# GTK3 editor:
windowrule = match:class nwg-look, float on, size 800 500

# File dialogs:
windowrule = match:class xdg-desktop-portal-gtk, center on float on size 900 600
windowrule = match:class google-chrome, match:title (Open|Save) Files, center on, float on, size 900 550


windowrule = workspace 4 silent, match:initial_class ^(discord)$

# PWAs
windowrule = workspace 3 silent, match:initial_title ^(Claude)$
windowrule = workspace 3 silent, match:initial_title ^(Gemini)$
windowrule = workspace 3 silent, match:initial_title ^(DeepSeek)$
windowrule = workspace 3 silent, match:initial_title ^(Perplexity)$
