[main]
shell=/usr/bin/zsh
font=JetBrainsMono Nerd Font Mono:size=12
font-italic=JetBrainsMono Nerd Font Mono:size=12
font-bold=JetBrainsMono Nerd Font Mono:size=12
line-height=19.416
letter-spacing=0

[bell]
system=no
urgent=no
notify=no
visual=no
command-focused=no

[scrollback]
lines=10000
multiplier=3.0

[url]
launch=xdg-open ${url}

[mouse]
hide-when-typing=yes
alternate-scroll-mode=yes

[cursor]
style=block
blink=yes
blink-rate=400
# beam-thickness=1

[colors-dark]
alpha=1
cursor=000000 FF00FF
# cursor=000000 FF007C # red
# cursor=000000 00FFFF # cyan
# cursor=000000 FF88000 # orange

[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
search-start=Control+Shift+r
