[main]
shell=/usr/bin/fish
font=JetBrainsMono Nerd Font Mono:size=12
font-italic=JetBrainsMono Nerd Font Mono:style=Italic:size=12
font-bold=JetBrainsMono Nerd Font Mono:style=Bold:size=12
font-bold-italic=JetBrainsMono Nerd Font Mono:style=Bold Italic:size=12
line-height=19.416
letter-spacing=0
term=foot
include=~/.config/foot/themes/vscode_dark.ini

[bell]
system=no
urgent=no
notify=no
visual=no
command-focused=no

[scrollback]
lines=10000

[url]
launch=xdg-open ${url}

[mouse]
hide-when-typing=yes
alternate-scroll-mode=yes

[cursor]
style=block
blink=yes
blink-rate=400
# beam-thickness=1
[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
search-start=Control+Shift+r

[colors-dark]
alpha=0.90
cursor=FFFFFF 9E3046
