# See https://wiki.hypr.land/Configuring/Keywords/
$mainMod = ALT # Sets "Alt" key as main modifier

# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $mainMod SHIFT, F, fullscreen, 0
bind = $mainMod , F, fullscreen, 1
bind = $mainMod, C, centerwindow
bind = $mainMod, Q, killactive,
bind = $mainMod SHIFT, Q, exec, $HOME/.config/hypr/scripts/exit-hypr.sh
bind = $mainMod SHIFT, E, exec, $HOME/.config/rofi/scripts/powermenu.sh
bind = $mainMod SHIFT, R, exec, hyprctl reload
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, P, pseudo,


bind = $mainMod, Return, exec, $terminal
# bind = $mainMod, D, exec, rofi -show drun
bind = $mainMod, D, exec, rofi -show drun
bind = $mainMod, B, exec, google-chrome-stable --ozone-platform=wayland
# bind = $mainMod, B, exec, firefox

# Focus window
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

# Move window
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, J, movewindow, d
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, L, movewindow, r

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, ampersand, workspace, 1
bind = $mainMod, eacute, workspace, 2
bind = $mainMod, quotedbl, workspace, 3
bind = $mainMod, apostrophe, workspace, 4
bind = $mainMod, parenleft, workspace, 5
bind = $mainMod, minus, workspace, 6
bind = $mainMod, egrave, workspace, 7
bind = $mainMod, underscore, workspace, 8
bind = $mainMod, ccedilla, workspace, 9
bind = $mainMod, agrave, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, ampersand, movetoworkspace, 1
bind = $mainMod SHIFT, eacute, movetoworkspace, 2
bind = $mainMod SHIFT, quotedbl, movetoworkspace, 3
bind = $mainMod SHIFT, apostrophe, movetoworkspace, 4
bind = $mainMod SHIFT, parenleft, movetoworkspace, 5
bind = $mainMod SHIFT, minus, movetoworkspace, 6
bind = $mainMod SHIFT, egrave, movetoworkspace, 7
bind = $mainMod SHIFT, underscore, movetoworkspace, 8
bind = $mainMod SHIFT, ccedilla, movetoworkspace, 9
bind = $mainMod SHIFT, agrave, movetoworkspace, 10

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
# bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Laptop multimedia keys for volume and LCD brightness
# bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
# bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
# bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
# bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
binde = , XF86AudioLowerVolume, exec, $HOME/.config/hypr/scripts/volume.sh --dec
binde = , XF86AudioRaiseVolume, exec, $HOME/.config/hypr/scripts/volume.sh --inc
bind = , XF86AudioMute, exec, $HOME/.config/hypr/scripts/volume.sh --toggle-mut
# bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
# bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-
binde = , XF86MonBrightnessDown, exec, $HOME/.config/hypr/scripts/backlight.sh --dec
binde = , XF86MonBrightnessUp, exec, $HOME/.config/hypr/scripts/backlight.sh --inc
binde = $mainMod SHIFT, DOWN ,  exec, $HOME/.config/hypr/scripts/backlight.sh --dec
binde = $mainMod SHIFT, UP ,  exec, $HOME/.config/hypr/scripts/backlight.sh --inc

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
