env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = ELECTRON_OZONE_PLATFORM_HINT,auto

env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0

env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1

monitor = eDP-1,1920x1080@144,0x0,1,vrr,1

$terminal = foot
$fileManager = nautilus

#for libadwaita gtk4 apps you can use this command:
exec-once = hypridle # Lock screen when idle.
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-light"
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --watch cliphist store # Clipboard.
# exec-once = nm-applet &
exec-once = waybar
exec-once = hyprsunset
exec-once = swaync
exec-once = swaybg -i $HOME/.config/hypr/walls/arch.png

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 2
    resize_on_border = true
    col.active_border = rgb(d0b5f3) # Purple border for active windows.
    allow_tearing = false
}

ecosystem {
    no_update_news = true
    no_donation_nag = true
}

decoration {
    rounding = 0
    rounding_power = 0

    blur {
        enabled = false
    }
}

cursor {
    no_hardware_cursors = false
}

animations {
    enabled = yes
    bezier = easeOut, 0.2, 1, 0.2, 1
    animation = windows, 1, 5, easeOut
    animation = windowsIn, 1, 5, default, popin
    animation = workspaces, 1, 5, default
}

master {
    new_status = master
}

misc {
    disable_hyprland_logo = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    vrr = 1 # Enables Variable Refresh Rate if supported
}

xwayland {
    force_zero_scaling = true
}

input {
    kb_layout = fr

    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat

    touchpad {
        natural_scroll = true
    }
}

source = $HOME/.config/hypr/binds.conf
source = $HOME/.config/hypr/window-rules.conf
