color=08052b ff7f7f
background=08052b
foreground=e3e3ea
# Normal (0–7)
regular0=08052b   # black  (bg repeated)
regular1=ff7f7f   # red
regular2=47b35d   # green
regular3=cc3980   # yellow (actually pink/magenta)
regular4=7fbaff   # blue
regular5=7f3fbf   # magenta/purple
regular6=7f7fff   # cyan
regular7=cdccdb   # white

# Bright (8–15)
bright0=7fbaff    # bright black
bright1=ff7f7f    # bright red
bright2=9999cc    # bright green
bright3=ff7f7f    # bright yellow
bright4=7f7fff    # bright blue
bright5=7f3fbf    # bright magenta
bright6=7f7fff    # bright cyan
bright7=e3e3ea    # bright white
