#Gruber Dark color scheme
cursor=e4e4ef 181818
background=181818
foreground=e4e4ef
#Normal colors
regular0=181818  # black
regular1=f43841  # red
regular2=73c936  # green
regular3=ffdd33  # yellow
regular4=96a6c8  # blue (niagara)
regular5=9e95c7  # magenta (wisteria)
regular6=95a99f  # cyan (quartz)
regular7=e4e4ef  # white
#Bright colors
bright0=52494e   # bright black
bright1=ff4f58   # bright red
bright2=73c936   # bright green
bright3=ffdd33   # bright yellow
bright4=96a6c8   # bright blue
bright5=9e95c7   # bright magenta
bright6=95a99f   # bright cyan
bright7=f4f4ff   # bright white
#Selection colors
selection-background=453d41
selection-foreground=f4f4ff
