[colors-dark]
cursor=FFFFFF 9E3046
background=101010
foreground=ffffff
#Normal colors
regular0=101010  # black
regular1=ff5733  # red
regular2=86cd82  # green
regular3=d9ba73  # yellow
regular4=666666  # blue (niagara)
regular5=f2a4db  # magenta (wisteria)
regular6=5abfb5  # cyan (quartz)
regular7=a5adce  # white
#Bright colors
bright0=666666   # bright black
bright1=ff7676   # bright red
bright2=a3d6a3   # bright green
bright3=ffffff   # bright yellow
bright4=b3b3b3   # bright blue
bright5=f4b8e4   # bright magenta
bright6=fafafa   # bright cyan
bright7=b5bfe2   # bright white
#Selection colors
selection-background=272727
selection-foreground=b0b0b0
